#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Runs as the backup user the Debian package created. Ready when 8007 answers.
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "curl -ks -o /dev/null https://127.0.0.1:8007/" \
        s6-setuidgid backup \
            /usr/lib/x86_64-linux-gnu/proxmox-backup/proxmox-backup-proxy
